INSERT INTO BookAuthor VALUES ("A01", "George Orwell");
INSERT INTO BookAuthor VALUES ("A02", "Gabriel Garcia Marquez");
INSERT INTO BookAuthor VALUES ("A03", "Aldous Huxley");
INSERT INTO BookAuthor VALUES ("A04", "Fyodor Dostoevsky");
INSERT INTO BookAuthor VALUES ("A05", "C.S. Lewis");
INSERT INTO BookAuthor VALUES ("A06", "Mary Shelley");
INSERT INTO BookAuthor VALUES ("A07", "John Steinbeck");
INSERT INTO BookAuthor VALUES ("A08", "Mark Twain");
INSERT INTO BookAuthor VALUES ("A09", "Charles Dickens");
INSERT INTO BookAuthor VALUES ("A10", "Joseph Heller");
INSERT INTO BookAuthor VALUES ("A11", "Homer");
INSERT INTO BookAuthor VALUES ("A12", "Victor Hugo");
INSERT INTO BookAuthor VALUES ("A13", "James Joyce");
INSERT INTO BookAuthor VALUES ("A14", "Vladimir Nabokov");
INSERT INTO BookAuthor VALUES ("A15", "Ayn Rand");
INSERT INTO BookAuthor VALUES ("A16", "Patrick Suskind");
INSERT INTO BookAuthor VALUES ("A17", "Franz Kafka");
INSERT INTO BookAuthor VALUES ("A18", "Bret Easton Ellis");
INSERT INTO BookAuthor VALUES ("A19", "Rene Goscinny");
INSERT INTO BookAuthor VALUES ("A19", "Albert Uderzo");
INSERT INTO BookAuthor VALUES ("A20", "Ray Bradbury");
INSERT INTO BookAuthor VALUES ("A21", "Isaac Asimov");
INSERT INTO BookAuthor VALUES ("A22", "Karl Marx");
INSERT INTO BookAuthor VALUES ("A22", "Friedrich Engels");
INSERT INTO BookAuthor VALUES ("A23", "Thomas Paine");
INSERT INTO BookAuthor VALUES ("A24", "Niccolo Machiavelli");
INSERT INTO BookAuthor VALUES ("A25", "Adam Smith");
INSERT INTO BookAuthor VALUES ("A26", "Miguel de Cervantes Saavedra");
INSERT INTO BookAuthor VALUES ("A27", "Simone de Beauvoir");
INSERT INTO BookAuthor VALUES ("A28", "Immanuel Kant");
INSERT INTO BookAuthor VALUES ("A29", "Charles Darwin");
INSERT INTO BookAuthor VALUES ("A30", "Isaac Newton");
INSERT INTO BookAuthor VALUES ("A31", "Milan Kundera");
INSERT INTO BookAuthor VALUES ("A32", "Sun Tzu");
INSERT INTO BookAuthor VALUES ("A33", "Jorge Luis Borges");
INSERT INTO BookAuthor VALUES ("A34", "Gabriel Garcia Marquez");
INSERT INTO BookAuthor VALUES ("A35", "Juan Rulfo");
INSERT INTO BookAuthor VALUES ("A36", "Octavio Paz");
INSERT INTO BookAuthor VALUES ("A37", "Pablo Neruda");
INSERT INTO BookAuthor VALUES ("A38", "Richard Feynman");
INSERT INTO BookAuthor VALUES ("A39", "Stephen Hawking");
INSERT INTO BookAuthor VALUES ("A40", "Carl Sagan");
INSERT INTO BookAuthor VALUES ("A41", "Silvanus P. Thompson");
INSERT INTO BookAuthor VALUES ("A41", "Martin Gardner");
INSERT INTO BookAuthor VALUES ("A42", "Enrico Fermi");
INSERT INTO BookAuthor VALUES ("A43", "Alexander Hamilton");
INSERT INTO BookAuthor VALUES ("A43", "James Madison");
INSERT INTO BookAuthor VALUES ("A43", "John Jay");
INSERT INTO BookAuthor VALUES ("A44", "John Lcke");
INSERT INTO BookAuthor VALUES ("A44", "C. B. Macpherson");
INSERT INTO BookAuthor VALUES ("A45", "Karl Popper");
INSERT INTO BookAuthor VALUES ("A46", "Howard Zinn");
INSERT INTO BookAuthor VALUES ("A47", "William Golding");
INSERT INTO BookAuthor VALUES ("A48", "George Orwell");
INSERT INTO BookAuthor VALUES ("A49", "Ernest Hemingway");
INSERT INTO BookAuthor VALUES ("A50", "Luo Guanzhong"); 